[package]
name = "region-nbt-rs"
version = "0.1.0"
edition = "2024"
#links = "region_rs"

[dependencies]
formatx = "0.2.4"
sysinfo = "0.38.1"
common-rs = { path = "../common-rs" }
gettext-rs = {version = "0.7.7", features = ["gettext-system"]}
zuri_nbt = "0.5.0"
zurinbt-common = { path = "../zurinbt-common" }

[lib]
crate-type = ["cdylib"]
