[package]
name = "dhlrc-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "1"
common-rs = { path = "../common-rs" }
gettext-rs = { version = "0.7.7", features = ["gettext-system"] }
formatx = "0.2.4"
notify = "8"

[lib]
# An `rlib` for the Rust frontends and a `cdylib` for the C/C++ ones.
crate-type = ["lib", "cdylib"]
