name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install cJSON from source
      run: |
        git clone https://github.com/DaveGamble/cJSON
        cd cJSON
        cmake -B build
        cmake --build build
        sudo cmake --install build
        cd ..

    - name: Install dhutil from source
      run: |
        sudo apt install -y gettext
        git clone https://github.com/DreamHelium/dhutil
        cd dhutil
        cmake -B build
        cmake --build build
        sudo cmake --install build
        cd ..

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.0.0
      with:
        version: 6.6.0 
        # Which might be defalut work on KDE 6

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} --install-prefix=${{github.workspace}}/pack

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: |
        cmake --install ${{github.workspace}}/build
        rm ${{github.workspace}}/pack/bin/dhlrc_qt

    - name: Install LinuxDeploy
      uses: miurahr/install-linuxdeploy-action@v1
      with:
        dir: ${{ github.workspace }}

    - name: Pack
      run : | 
        apt install appstream libfuse2
        ./linuxdeploy-x86_64.AppImage --appdir ${{github.workspace}}/pack --executable ${{github.workspace}}/build/dhlrc_qt -d ${{github.workspace}}/dhlrc_qt.desktop -i ${{github.workspace}}/dhlrc_qt.png --output appimage

    - name: Upload
      uses: actions/upload-artifact@v4.3.3
      with:
          name: dhlrc_qt-x86_64.AppImage
          path: dhlrc_qt-x86_64.AppImage
      
